= Basic Tutorial for faggregate
:author: Thibault Morin
:docdatetime: 2024-02-18
:revnumber: 2
:toc:
:source-highlighter: coderay
:doctype: article
:description: Elevate your DDD implementation with this tutorial on a Java library that blends Aggregates & functional programming. Gain hands-on expertise now!

[abstract]
== Abstract

[Abstract]

This document presents a comprehensive guide aimed at facilitating the implementation of Domain Driven Design (DDD) by integrating the `faggregate` library, which harmoniously combines the concepts of Aggregates with functional programming paradigms.
The library is designed to offer developers an efficient means to navigate and simplify intricate development challenges.
Through practical exercises and detailed explanations, this tutorial aims to equip readers with the necessary skills and knowledge to adeptly apply the library's functionalities.

== Introduction

`faggregate` is a Java library helping to define Aggregate according to the _Domain Driven Design_ approach with a touch of _Functional Programming_. The source code of `faggregate` is available on link:https://github.com/tmorin/faggregate[github.com/tmorin/faggregate].

`faggregate` synthesizes the robust methodologies of DDD Aggregates and functional programming to streamline the software development process.

DDD Aggregates offer a structured approach to managing complex domain entities and ensuring transactional consistency.
In parallel, functional programming emphasizes a declarative coding style, enhancing code clarity and simplifying maintenance efforts.
The amalgamation of these methodologies not only fosters more stable and reliable software but also minimizes the incidence of defects.

Furthermore, the emphasis on functional programming augments code modularity and facilitates straightforward refactoring, attributes highly beneficial in the context of extensive software development endeavors.

In essence, `faggregate` empowers developers to create systems that are both scalable and maintainable, adeptly addressing the needs of their specific business domains.

== The scope

The purpose of this tutorial is to build from scratch the `Counter` aggregate.
As its name suggests, the `Counter` aggregate is capable of tracking a value that is incremented.
The counter is incremented when the `CounterIncremented` domain event is produced.
The event is produced when the `IncrementCounter` command is invoked.

.Modeling of the `IncrementCounter` command
[plantuml,target=es_increment,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
Aggregate('Counter')
Command('IncrementCounter')
DomainEvent('CounterIncremented')
IncrementCounter .. Counter : 1. invoked on
IncrementCounter -r-> CounterIncremented : 2. produces
CounterIncremented .. Counter : 3. applied on
....

In this tutorial, we will cover a series of foundational steps necessary for building a robust application using the framework.
This journey will begin with bootstrapping a Maven project, setting the groundwork for our development process.
We will then delve into defining the Counter aggregate, a core component of our application's domain model.
Following this, we'll tackle implementing the command handler for the IncrementCounter command, allowing us to interact with our aggregate.
We'll also implement the mutator for the CounterIncremented domain event to handle state changes.
The creation of the repository for the Counter aggregate will be our next step, ensuring we have a solid persistence mechanism.
We'll continue with implementing the configurer of the Counter aggregate, tying all components together for a cohesive application configuration.
Finally, we'll explore the validation of the Counter aggregate, ensuring that our implementation meets the requirements of our business domain.

The source code of the tutorial is available on link:https://github.com/tmorin/faggregate/tree/main/examples/tutorial[github.com/tmorin/faggregate].

== The Maven module

The Maven module brings four dependencies.
The first one, `faggregate-core-simple`, brings the `faggregate` library.
The second one, `faggregate-core-scenario`, brings an extension of `faggregate` library to implement acceptance tests.
The third one, link:https://junit.org/junit5/docs/current/user-guide/[`junit-jupiter`], provides a test framework.
Finally, link:https://projectlombok.org/[`lombok`], _spices_ up java helping to save lines of codes.

[source,xml,title=./pom.xml]
----
include::../../pom.example.xml[]
----

== The Aggregate

The implementation of the Aggregate starts with the structural elements:

- *Entity*: it's an object within the system that has a unique identity and attributes that describe its state.
An entity's identity is typically represented by an ID or a key, and its state changes over time as it participates in the system's interactions.
- *Command*: it's a request for the system to perform a specific action.
Commands are often used to initiate changes in the state of the system.
- *Domain Event*: it's a record of something that has occurred within the system.
Domain events are used to capture the state changes that occur as a result of processing commands.

=== The Root Aggregate

A Root Aggregate is a cluster of related entities that are treated as a single unit with respect to transactions and consistency.
The root aggregate defines a boundary around a set of related entities, and it is responsible for ensuring that changes to its entities are made in a consistent and valid state.

In this tutorial, the Root Aggregate of the `Counter` Aggregate, is the `Counter` Entity.
Usually, a Root Aggregate is an Entity which is mutable.
However, `faggregate` emphasizes a functional approach, therefore the Root Aggregate is an immutable structure.

[source,java,title=src/main/java/faggregate/tutorial/Counter.java]
----
include::../../src/main/java/faggregate/tutorial/Counter.java[]
----

The Root Aggregate is covered by the following unit test.

[source,java,title=src/test/java/faggregate/tutorial/CounterTest.java]
----
include::../../src/test/java/faggregate/tutorial/CounterTest.java[]
----

=== The Command

The `IncrementCounter` Command transfers the intention to increment the counter.

[source,java,title=src/main/java/faggregate/tutorial/IncrementCounter.java]
----
include::../../src/main/java/faggregate/tutorial/IncrementCounter.java[]
----

=== The Domain Event

The `CounterChanged` Domain Event states the value of a counter has been changed.

[source,java,title=src/main/java/faggregate/tutorial/CounterChanged.java]
----
include::../../src/main/java/faggregate/tutorial/CounterChanged.java[]
----

== The Command Handler

A Command Handler is a pure function which executes a Command according to the latest known state of an Aggregate.
A Command Handler returns a Result which will be sent back to the initiator of the command as well as a set of Domain Events explaining the outcome of the Command execution.

.Input and output of a command handler
[plantuml,target=obj_command_handler,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "command" as command
rectangle "result" as result
rectangle "domain events" as domain_events
rectangle "aggregate state" as aggregate
rectangle "command handler" as command_handler
command --> command_handler
aggregate --> command_handler
command_handler --> result
command_handler --> domain_events
....

The `IncrementCounterHandler` Command Handler handles the `IncrementCounter` Command and produces the `CounterChanged` Domain Event based on the latest known state of the `Counter` Aggregate.

[source,java,title=src/main/java/faggregate/tutorial/IncrementCounterHandler.java]
----
include::../../src/main/java/faggregate/tutorial/IncrementCounterHandler.java[]
----

The Command Handler is covered by the following unit test.

[source,java,title=src/test/java/faggregate/tutorial/IncrementCounterHandlerTest.java]
----
include::../../src/test/java/faggregate/tutorial/IncrementCounterHandlerTest.java[]
----

== The Mutator

A Mutator is a pure function which mutates the state of an Aggregate according to a Domain Event.
A Mutator returns a new instance of the Aggregate state.

.Input and output of a mutator
[plantuml,target=obj_mutator,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "domain event" as domain_event
rectangle "aggregate state" as aggregate
rectangle "new aggregate state" as new_aggregate
rectangle "mutator" as mutator
domain_event --> mutator
aggregate --> mutator
mutator --> new_aggregate
....

The `CounterChangedMutator` Mutator mutates the state of the `Counter` Aggregate according to the `CounterChangedMutator` Domain Event.

[source,java,title=src/main/java/faggregate/tutorial/CounterChangedMutator.java]
----
include::../../src/main/java/faggregate/tutorial/CounterChangedMutator.java[]
----

The Mutator is covered by the following unit test.

[source,java,title=src/test/java/faggregate/tutorial/CounterChangedMutatorTest.java]
----
include::../../src/test/java/faggregate/tutorial/CounterChangedMutatorTest.java[]
----

== The Repository

A repository is a set of functions which initiates, loads, persists and destroys the state of an Aggregate.

=== Side effects

In `faggregate`, we define those functions as side effects:

- *initializer*: it initializes the state of an Aggregate
- *loader*: it loads the latest known state of an Aggregate
- *persister*: it persists the latest known state and/or the generated Domain Events of an Aggregate
- *destroyer*: it destroys the persisted data related to an Aggregate

The side effects are applied according to the intention of the handled command.
For instance, the *initializer* is executed when a Command Handler has been registered with the `INITIALIZATION` intention. The details of the intentions are explained in the following sections.

=== The Initializer

An initializer is executed when the type of the handled Command has been registered with the `INITIALIZATION` intention.

.Input and output of an initializer
[plantuml,target=obj_initializer,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "aggregate identifier" as aggregate_identifier
rectangle "command" as command
rectangle "aggregate state" as aggregate
rectangle "initializer" as initializer
aggregate_identifier --> initializer
command --> initializer
initializer --> aggregate
....

In this tutorial, the initializer is not implemented because there is no command handled with the `INITIALIZATION` intention.

=== The Loader

A loader is executed when the type of the handled Command has been registered with the `MUTATION` intention.

.Input and output of a loader
[plantuml,target=obj_loader,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "aggregate identifier" as aggregate_identifier
rectangle "aggregate state" as aggregate
rectangle "loader" as loader
aggregate_identifier --> loader
loader --> aggregate
....

In this tutorial, the loader is implemented because the `IncrementCounter` command is handled with the `MUTATION` intention.

=== The Persister

A persister is executed when the type of the handled Command has been registered with the `INITIALIZATION` or `MUTATION` intentions.

.Input and output of a persister
[plantuml,target=obj_persister,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "aggregate identifier" as aggregate_identifier
rectangle "aggregate state" as aggregate
rectangle "persister" as persister
rectangle "domain events" as events
aggregate_identifier --> persister
aggregate --> persister
events --> persister
....

In this tutorial, the persister is implemented because the `IncrementCounter` command is handled with the `MUTATION` intention.

=== The Destroyer

A destroyer is executed when the type of the handled command has been registered with the `DESTRUCTION` intention.

.Input and output of a destroyer
[plantuml,target=obj_destroyer,format=svg]
....
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/eventstorming/single.puml
rectangle "aggregate identifier" as aggregate_identifier
rectangle "aggregate state" as aggregate
rectangle "domain events" as events
rectangle "destroyer" as destroyer
aggregate_identifier --> destroyer
aggregate --> destroyer
events --> destroyer
....

In this tutorial, the destroyer is not implemented because there is no command handled with the `DESTRUCTION` intention.

=== The implementation

[source,java,title=src/main/java/faggregate/tutorial/CounterRepository.java]
----
include::../../src/main/java/faggregate/tutorial/CounterRepository.java[]
----

The Repository is covered by the following unit test.

[source,java,title=src/test/java/faggregate/tutorial/CounterRepositoryTest.java]
----
include::../../src/test/java/faggregate/tutorial/CounterRepositoryTest.java[]
----

== The Configurer

A Configurer binds the handlers, mutators and all side effects of an Aggregate.
For ease, there is only one Configurer of the Counter Aggregate.
In fact, in production grade project, there is Configured for the core domain and also ones in infrastructure,
e.g. one for a relational database, another one for an in memory storage ....

[source,java,title=src/main/java/faggregate/tutorial/CounterConfigurer.java]
----
include::../../src/main/java/faggregate/tutorial/CounterConfigurer.java[]
----

The Configurer is covered by the following unit test.

[source,java,title=src/test/java/faggregate/tutorial/CounterConfigurerTest.java]
----
include::../../src/test/java/faggregate/tutorial/CounterConfigurerTest.java[]
----

== The validation

The building blocks offered by `faggregate` facilitate the separation of the API, core, and side effects layers.
This architecture allows the core to define acceptance scenarios with commands, events, and states, essential for validating the implementations of side effects.
Consequently, side effects are testable from the core's perspective, which is crucial for ensuring that business rules are correctly implemented and accepted.
This design principle underpins the framework's approach to robust, domain-driven application development.

In this tutorial, we explore two key scenarios using `faggregate`: the creation and the incrementation of a counter, both of which are organized within the same suite. In the context of `faggregate`, a suite refers to a collection of acceptance scenarios.

A scenario follows the _Given-When-Then_ pattern, which is a widely used format for writing acceptance tests. It consists of three parts:

- *Given*: the initial state of the system
- *When*: the action that triggers the change in the system
- *Then*: the expected outcome of the action

The acceptance suite of the Counter aggregate is provided by the following factory.

[source,java,title=src/main/java/faggregate/tutorial/CounterSuiteFactory.java]
----
include::../../src/main/java/faggregate/tutorial/CounterSuiteFactory.java[]
----

The execution of the acceptance suite is handled by a usual JUnit test.

[source,java,title=src/main/java/faggregate/tutorial/CounterSuiteFactory.java]
----
include::../../src/test/java/faggregate/tutorial/CounterSuiteTest.java[]
----

== Conclusion

In conclusion, this tutorial offers a comprehensive exploration of the `faggregate` Java library, a potent resource for developers aiming to integrate Domain Driven Design Aggregates with functional programming principles.
Through the meticulous construction of the Counter aggregate example, it showcases how `faggregate` simplifies the development of complex, domain-centric software systems, promoting maintainability and scalability.

The step-by-step guidance provided throughout the tutorial, from setting up a Maven project to implementing domain-specific logic and persistence mechanisms, equips developers with the tools and knowledge needed to fully harness the capabilities of `faggregate`.
This approach not only facilitates the building of high-quality software that aligns with business requirements but also enhances the overall development experience by leveraging functional programming's strengths in clarity, modularity, and immutability.

As a valuable educational resource, the tutorial underscores the significance of adopting DDD Aggregates and functional programming in modern software development.
It empowers developers to create software systems that are not only robust and scalable but also aligned with the strategic goals of their business domains.
Thus, for those seeking to deepen their understanding of DDD and functional programming or to elevate the quality of their software projects, this tutorial proves to be an indispensable guide.
